// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimPim.Api.Data;

#nullable disable

namespace SimPim.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251106072836_AddDataRezultateToComanda")]
    partial class AddDataRezultateToComanda
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SimPim.Api.Models.ComandaInvestigatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodInvestigatie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataComanda")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataInvestigatie")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataRezultate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DenumireInvestigatie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InvestigatieId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ComenziInvestigatii");
                });

            modelBuilder.Entity("SimPim.Api.Models.Investigatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Cod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Investigatii");
                });

            modelBuilder.Entity("SimPim.Api.Models.ParametruInvestigatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodParametru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("InvestigatieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Unitate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("ValoareMax")
                        .HasColumnType("REAL");

                    b.Property<double?>("ValoareMin")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("InvestigatieId");

                    b.ToTable("ParametriInvestigatii");
                });

            modelBuilder.Entity("SimPim.Api.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adresa")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataInregistrarii")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("DataNastere")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gen")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("IDNP")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IDNP")
                        .IsUnique();

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("SimPim.Api.Models.RezultatInvestigatie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CodParametru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ComandaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DenumireParametru")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Interpretare")
                        .HasColumnType("TEXT");

                    b.Property<string>("Unitate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Valoare")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ComandaId");

                    b.ToTable("RezultateInvestigatii");
                });

            modelBuilder.Entity("SimPim.Api.Models.ParametruInvestigatie", b =>
                {
                    b.HasOne("SimPim.Api.Models.Investigatie", null)
                        .WithMany("Parametri")
                        .HasForeignKey("InvestigatieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimPim.Api.Models.RezultatInvestigatie", b =>
                {
                    b.HasOne("SimPim.Api.Models.ComandaInvestigatie", null)
                        .WithMany("Rezultate")
                        .HasForeignKey("ComandaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimPim.Api.Models.ComandaInvestigatie", b =>
                {
                    b.Navigation("Rezultate");
                });

            modelBuilder.Entity("SimPim.Api.Models.Investigatie", b =>
                {
                    b.Navigation("Parametri");
                });
#pragma warning restore 612, 618
        }
    }
}
